# syntax=docker/dockerfile:1.7

ARG CADDY_BASE_REPOSITORY=docker.io/library/caddy
ARG CADDY_BASE_DIGEST=sha256:98eb57d882ccd5213d1688764db10c1ca2c58a1ca3a6717a3411ad798f7a423a

FROM ${CADDY_BASE_REPOSITORY}@${CADDY_BASE_DIGEST}
RUN setcap -r /usr/bin/caddy \
    && test -z "$(getcap /usr/bin/caddy)" \
    && apk del libcap
USER 10004:11003
